name: vo_research
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - numpy=2.3.5
  - scipy=1.18.0
  - pandas=3.0.5
  - matplotlib=3.10.7
  - seaborn=0.13.2
  - pip
  - pip:
    - evo==1.37.0
    - opencv-python==4.10.0
